config/routes.rb
Rails.application.routes.draw do
  root 'pages#home'
  get 'apply', to: 'pages#apply', as: 'apply'
  get 'thanks', to: 'pages#thanks', as: 'thanks'
  get 'start', to: 'pages#start', as: 'start'
  get 'magic_login', to: 'pages#magic_login', as: 'magic_login'

  devise_for :users
  get 'logout', to: 'pages#logout', as: 'logout'
  get 'login', to: redirect(path: '/users/sign_in')

  resources :subscribe, only: [:index]
  get 'dashboard', to: 'dashboard#index'

  # get 'stakeholder_updates/new', to: 'stakeholder_updates#new'
  resources :stakeholder_updates, only: %i[new create edit show update]
  resources :updates, only: [:show]

  resources :account, only: %i[index update]
  resources :billing_portal, only: [:create]
  match '/billing_portal' => 'billing_portal#create', via: [:get]
  match '/cancel' => 'billing_portal#destroy', via: [:get]

  resources :user_submissions, only: [:create]
  resources :projects, only: [:update]
  resources :subscribers, only: %i[create destroy]

  # static pages
  pages = %w[
    privacy terms
  ]

  pages.each do |page|
    get "/#{page}", to: "pages##{page}", as: "#{page.gsub('-', '_')}"
  end

  # admin panels
  authenticated :user, -> user { user.admin? } do
    namespace :admin do
      get '/', to: 'pages#dashboard'
      resources :user_submissions, only: [:update]
    end
  end
end

app/views/admin/pages/dashboard.html.erb
<%= render partial: 'shared/heading', locals: { title: 'Admin Panel', tagline: 'Accept or reject applications.' } %>

<div class="px-4 sm:px-6 lg:px-8">
  <div class="mt-8 flow-root">
    <div class="-mx-4 -my-2 overflow-x-auto sm:-mx-6 lg:-mx-8">
      <div class="inline-block min-w-full py-2 align-middle sm:px-6 lg:px-8">
        <table class="min-w-full divide-y divide-gray-300">
          <thead>
            <tr>
              <th scope="col" class="py-3.5 pl-4 pr-3 text-left text-sm font-semibold text-gray-900 sm:pl-0">Name</th>
              <th scope="col" class="px-3 py-3.5 text-left text-sm font-semibold text-gray-900">Plan</th>
              <th scope="col" class="px-3 py-3.5 text-left text-sm font-semibold text-gray-900">Email</th>
              <th scope="col" class="px-3 py-3.5 text-left text-sm font-semibold text-gray-900">Website</th>
              <th scope="col" class="px-3 py-3.5 text-left text-sm font-semibold text-gray-900">Role</th>
              <th scope="col" class="px-3 py-3.5 text-left text-sm font-semibold text-gray-900">Newsletter</th>
              <th scope="col" class="relative py-3.5 pl-3 pr-4 sm:pr-6">
                <%# <span>Placeholder</span> %>
              </th>
            </tr>
          </thead>
          <tbody class="divide-y divide-gray-200 bg-white">
            
            <% @user_submissions.each do |user_submission| %>
              <tr>
                <td class="whitespace-nowrap py-5 pl-4 pr-3 text-sm sm:pl-0">
                  <div class="flex items-center">
                    <div class="h-11 w-11 flex-shrink-0">
                      <img class="h-11 w-11 rounded-full" src="https://images.unsplash.com/photo-1517841905240-472988babdf9?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=facearea&facepad=2&w=256&h=256&q=80" alt="">
                    </div>
                    <div class="ml-4">
                      <div class="font-me dium text-gray-900"><%= user_submission.name %></div>
                    </div>
                  </div>
                </td>
                <td class="whitespace-nowrap px-3 py-5 text-sm text-gray-500"><%= user_submission.plan_name %></td>
                <td class="whitespace-nowrap px-3 py-5 text-sm text-gray-500"><%= user_submission.email %></td>
                <td class="whitespace-nowrap px-3 py-5 text-sm text-gray-500"><%= user_submission.website %></td>
                <td class="whitespace-nowrap px-3 py-5 text-sm text-gray-500"><%= user_submission.job_role %></td>
                <td class="px-3 py-5 text-sm text-gray-500 max-w-xs">
                  <div class="text-gray-900"><%= user_submission.text %></div>
                </td>
                <td class="relative whitespace-nowrap py-5 pl-3 pr-4 text-right text-sm font-medium sm:pr-0">
                  <div>
                      <%= form_for user_submission, url: admin_user_submission_path(user_submission.id) do |f| %>
                        <select id="user_submission_status" name="user_submission[status]" class="mt-1 block w-full rounded-md border-gray-300 py-2 pl-3 pr-10 text-base focus:border-indigo-500 focus:outline-none focus:ring-indigo-500 sm:text-sm">
                          <option <%= 'selected' if user_submission.status.nil? %>>Pending</option>
                          <option <%= 'selected' if user_submission.status == 'Accept' %>>Accept</option>
                          <option <%= 'selected' if user_submission.status == 'Reject' %>>Reject</option>
                        </select>
                        <%= f.submit "Update", class: "w-full rounded-md bg-brand-purple-light my-2 px-3 py-2 text-sm font-semibold text-white shadow-sm hover:bg-brand-purple focus-visible:outline focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-brand-gold" %>
                      <% end %>
                  </div>
                </td>
              </tr>
            <% end %>

            <!-- More people... -->
          </tbody>
        </table>
      </div>
    </div>
  </div>
</div>