config/routes.rb
Rails.application.routes.draw do
  root 'pages#home'
  get 'apply', to: 'pages#apply', as: 'apply'
  get 'thanks', to: 'pages#thanks', as: 'thanks'
  get 'start', to: 'pages#start', as: 'start'
  get 'magic_login', to: 'pages#magic_login', as: 'magic_login'

  devise_for :users
  get 'logout', to: 'pages#logout', as: 'logout'
  get 'login', to: redirect(path: '/users/sign_in')

  resources :subscribe, only: [:index]
  get 'dashboard', to: 'dashboard#index'

  # get 'stakeholder_updates/new', to: 'stakeholder_updates#new'
  resources :stakeholder_updates, only: %i[new create edit show update]
  resources :updates, only: [:show]

  resources :account, only: %i[index update]
  resources :billing_portal, only: [:create]
  match '/billing_portal' => 'billing_portal#create', via: [:get]
  match '/cancel' => 'billing_portal#destroy', via: [:get]

  resources :user_submissions, only: [:create]
  resources :projects, only: [:update]
  resources :subscribers, only: %i[create destroy]

  # static pages
  pages = %w[
    privacy terms
  ]

  pages.each do |page|
    get "/#{page}", to: "pages##{page}", as: "#{page.gsub('-', '_')}"
  end

  # admin panels
  authenticated :user, -> user { user.admin? } do
    namespace :admin do
      get '/', to: 'pages#dashboard'
      resources :user_submissions, only: [:update]
    end
  end
end

app/controllers/subscribe_controller.rb
class SubscribeController < ApplicationController
  before_action :authenticate_user!
  before_action :maybe_skip_onboarding

  def index
  end
end

app/views/subscribe/index.html.erb
<%= render partial: "shared/heading", locals: { title: 'Start your Plan', tagline: "Start your Pro subscription today for unlimited access to founder uptades." } %>

<div class="text-center">
  <!-- provide an image to compel user to add payment details -->
  <!-- <%= image_path "", style: "display: inline-block; max-height: 375px;", class: "mt-6 object-center" %> -->
</div>

<p class="mt-12 text-center">Click here to choose a plan and activate your account.</p>
<div class="mt-2 justify-center text-center">
  <div class="text-center inline-flex rounded-md shadow">
    <button onclick="beginSubscription()" type="submit" class="items-center justify-center px-5 py-3 border border-transparent text-base font-medium rounded-md text-white bg-indigo-600 hover:bg-indigo-700">
      Subscribe for $99 /year
    </button>
  </div>
  <div class="mt-2 text-center">
    <a href="mailto:support@foundrdigest.com" class="font-medium text-indigo-300 hover:text-indigo-500">Still have questions?</a>
  </div>
</div>

<script type="text/javascript">
  var beginSubscription = function() {
    console.log('building subscription...');

    $.ajax({
      url: '<%= billing_portal_index_path %>',
      method: 'POST',
      dataType: 'json',
      data: {},
      success: function(data) {
        console.log('success! portal url: ', data.url)
        window.location.href = data.url;
      },
      error: function(data) {
        window.alert('Sorry, something went wrong. Please try again.');
      }
    })
  }
</script>